############################################################
# STEPS

# Steps to be done
steps: ["preprocessing", "taxonomy", "assembly", "contig_taxonomy", "kaiju", "annotation", "functions", "coverage"] #, "seed", "binning"] #TODO: "eukaryotes", "coassembly"


############################################################
# INPUT
# Directory where the workflow exists
work_dir: "/ssd0/susbus/ea_biofilm/metag_analyses"

# Directory where the data files are
data_dir: "/hdd0/raid3/scratch/MEGshared/ea_biofilm/data" # USER_INPUT

# Directory for the results
results_dir: "/prj/DECODE/ea_biofilm_results" #"/hdd0/raid3/scratch/MEGshared/ea_biofilm/results" # USER_INPUT

# Directory where the conda environments are
env_dir: "/ssd0/susbus/ea_biofilm/metag_analyses/envs"

# Directory with scripts
src_dir: "/ssd0/susbus/ea_biofilm/metag_analyses/scripts"

# Samples (if a relative path, relative to this repo)
samples: "config/samples.tsv" # USER_INPUT

############################################################
# TOOLS 
# PREPROCESSING
trim_galore:
  threads: 16

# FILTERING 
filter:
  fasta: "/hdd0/susbus/databases/hg38/GRCh38_latest_genomic.fna" # Downloaded on 2023-11-16 from https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz

# QUALITY
fastqc:
  threads: 4

# CLASSIFICATION
kraken2:
  db: "/hdd0/susbus/databases/kraken2/pluspfp/"
  confidence: 0.2
  contig_confidence: 0.2
  threads: 12
  read: 150
  level: "S" # https://github.com/jenniferlu717/Bracken/issues/117
  contig_level: "S" # set to phylum since many samples were unclassified at the Species, Genus, Family and Order levels

# KAIJU
kaiju:
  threads: 12
  level: "species"
  fmi: "/hdd0/susbus/databases/kaiju/kaiju_db_nr_euk.fmi"
  nodes: "/hdd0/susbus/databases/kaiju/nodes.dmp"
  names: "/hdd0/susbus/databases/kaiju/names.dmp"

# Struo2 database from the Ruth Ley lab
struo2_kraken2:
  db: "/hdd0/susbus/databases/kraken2/"
  threads: 12

# Bracken
# Bracken installed based on information here: https://github.com/jenniferlu717/Bracken
bracken:
  bin: "/hdd0/susbus/tools/Bracken/bracken"
  combine: "/hdd0/susbus/tools/Bracken/analysis_scripts/combine_bracken_outputs.py"

# MEGAHIT
# https://github.com/voutcn/megahit
megahit:
  threads: 36
  coassembly_threads: 70

# DE-DUPLICATION
clumpify:
  threads: 64
  dupedist: 12000
  groups: 50
  memory: "1600g"

# ANNOTATION
prodigal:
  threads: 12

# Eukaryotes
eukulele:
  threads: 64
  db: "phylodb"
  aligner: "diamond"  # options: "blast" or "diamond"
  scratch: "/hdd0/susbus/socd/results/eukulele_scratch"
  ref_dir: "/hdd0/susbus/databases"

# MAPPING
bwa:
  threads: 10
  map_threads: 16

# http://www.htslib.org/doc/samtools.html
samtools:
  sort:
    chunk_size: "4G"
    chunk_size_bigmem: "16G"  

# MagicLamp
# https://github.com/Arkadiy-Garber/MagicLamp
magiclamp:
  threads: 36

# EGGNOG
# https://github.com/eggnogdb/eggnog-mapper
eggnog:
  db: "/hdd0/susbus/databases/eggnog" ###USER INPUT REQUIRED###
  threads: 16
  final_threads: 24
  itype: "proteins"  # chose 'metagenome' if prediction is used
  genepred: "prodigal"
  split:
    length: 2000000
    suffix: 3

# SEED
# https://github.com/transcript/samsa2
seed:
  db: "/raid1/scratch/MEGshared/MG_packages/samsa2/full_databases"
  dmnd_db: "/raid1/scratch/MEGshared/MG_packages/samsa2/full_databases/subsys_db.dmnd"
  fa_db: "/raid1/scratch/MEGshared/MG_packages/samsa2/full_databases/subsys_db.fa"
  threads: 24

# BINNING
filter_length:
    threads: 4
    
mdmcleaner:
    threads: 7

mapping:
    threads: 7

metabat2:
    threads: 14

concoct:
    threads: 14

metabinner:
    length: 2000
    threads: 14

dasTool:
    threads: 14

checkm:
    threads: 14

drep:
    threads: 28
    comp: 70
    cont: 10

gtdbtk:
    threads: 14
    path: "/scratch/users/gmichoud/DB/release207_v2"
