############################################################
# STEPS

# Steps to be done
steps: ["taxonomy", "assembly", "contig_taxonomy", "annotation", "kaiju", "coverage"] #TODO: "eukaryotes", "coassembly"


############################################################
# INPUT
# Directory where the workflow exists
work_dir: "/ssd0/susbus/socd/metag_analyses"

# Directory where the data files are
data_dir: "/ssd0/susbus/socd/data/preprocessed" #"/hdd0/susbus/nf_core/data/hebe_16S"

# Directory for the results
results_dir: "/hdd0/susbus/socd/results"

# Directory where the conda environments are
env_dir: "/ssd0/susbus/socd/metag_analyses/envs"

# Directory with scripts
src_dir: "/ssd0/susbus/socd/metag_analyses/scripts"
  
############################################################
# TOOLS 
# CLASSIFICATION
kraken2:
  db: "/hdd0/susbus/databases/kraken2/pluspfp/"
  confidence: 0.5
  contig_confidence: 0.2
  threads: 12
  read: 150
  level: "S" # https://github.com/jenniferlu717/Bracken/issues/117
  contig_level: "P" # set to phylum since many samples were unclassified at the Species, Genus, Family and Order levels

# KAIJU
kaiju:
  threads: 4
  level: "species"
  fmi: "/hdd0/susbus/databases/kaiju/kaiju_db_nr_euk.fmi"
  nodes: "/hdd0/susbus/databases/kaiju/nodes.dmp"
  names: "/hdd0/susbus/databases/kaiju/names.dmp"

# Struo2 database from the Ruth Ley lab
struo2_kraken2:
  db: "/hdd0/susbus/databases/kraken2/"
  threads: 12

# Bracken
# Bracken installed based on information here: https://github.com/jenniferlu717/Bracken
bracken:
  bin: "/hdd0/susbus/tools/Bracken/bracken"
  combine: "/hdd0/susbus/tools/Bracken/analysis_scripts/combine_bracken_outputs.py"

# MEGAHIT
# https://github.com/voutcn/megahit
megahit:
  threads: 12
  coassembly_threads: 70

# DE-DUPLICATION
clumpify:
  threads: 64
  dupedist: 12000
  groups: 50
  memory: "1600g"

# ANNOTATION
prodigal:
  threads: 8

# Eukaryotes
eukulele:
  threads: 64
  db: "phylodb"
  aligner: "diamond"  # options: "blast" or "diamond"
  scratch: "/hdd0/susbus/socd/results/eukulele_scratch"
  ref_dir: "/hdd0/susbus/databases"

# MAPPING
bwa:
  threads: 10
  map_threads: 16

# http://www.htslib.org/doc/samtools.html
samtools:
  sort:
    chunk_size: "4G"
    chunk_size_bigmem: "16G"  
