$schema: "http://json-schema.org/draft-07/schema#"

title: "main config file"

properties:
#  tag:
#    type: string
#  workdir:
#    type: string
  results_dir:
    type: string
#  dbsdir:
#    type: string
  samples:
    type: string

required:
  - results_dir
  - samples
